#!/bin/bash
export LC_ALL=en_US.utf8

SSHPORT='22'
ZONE='Asia/Shanghai'
cat > /etc/default/locale <<EOF
#  File generated by update-locale
LANG="en_US.UTF-8"
LANGUAGE="en_US.en"
EOF
locale-gen en_US.UTF-8
apt update
apt install -y systemd logrotate ncat lldpd curl ethtool lsscsi ntpdate smartmontools network-manager vim openssh-server ifupdown net-tools netplan.io sysstat python3-pip jq netcat xfsprogs bind9-dnsutils iproute2 tcpdump

systemctl start lldpd && systemctl enable lldpd
timedatectl set-timezone $ZONE
timedatectl set-ntp 0
timedatectl set-local-rtc 0
ntpdate pool.ntp.org
cat > /etc/cron.d/xxxx <<EOF
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
CRON_TZ=$ZONE
*/15 * * * * root (ntpdate pool.ntp.org)
EOF

#sshd config
mkdir -p /root/.ssh/
curl -X GET -o ~/.ssh/authorized_keys http://xxxxxxxxxxxxxxxxxx/authorized_keys
chmod 0400 ~/.ssh/*
grep -iq shaohy /root/.ssh/authorized_keys

[ $? = 0 ] && sed -r -i "/#Port 22/s^.*^Port $SSHPORT^g;s/#PermitRootLogin prohibit-password/PermitRootLogin yes/g" /etc/ssh/sshd_config  && sed -r -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
sed -r -i 's@weekly@daily@g;s@^rotate.*@rotate 7@g;s@^#compress.*@compress@g' /etc/logrotate.conf
sed -r -i -e '/Compress=/s@.*@Compress=yes@g; /SystemMaxUse=/s@.*@SystemMaxUse=4G@g; ' \
 -e '/SystemMaxFileSize=/s@.*@SystemMaxFileSize=256M@g; /MaxRetentionSec=/s@.*@MaxRetentionSec=2week@g' /etc/systemd/journald.conf
